# -*- coding: utf-8 -*-
"""Acoes_magalu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1keSh2CrYsFV3ESJ8Wdsdi_c6UP6HAlLq
"""

# Base de Dados para Download
base_dados_link = 'https://docs.google.com/spreadsheets/d/1r0_Vs5QX1ef5X1MZCbDg8kcqm-my3rSn/edit?usp=sharing&ouid=108903987275959757465&rtpof=true&sd=true'
print(base_dados_link)

# Importando Bibliotecas

# Bibliotecas para Modelagem e Matrizes
import pandas as pd
import numpy as np

# Bibliotecas para análises Gráficas
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

# Lendo o arquivo e buscando as pimeiras Linhas

acoes_magalu = pd.read_excel('Vase_004 - Magalu - Sem Resolução.xlsx')
acoes_magalu.head()

# Ultimas Linhas

acoes_magalu.tail()

# Verificando

acoes_magalu.shape

acoes_magalu.info()

acoes_magalu.describe()

# Series Temporais
dados = acoes_magalu.set_index('Data')

dados.head()

plt.style.use('fivethirtyeight')
plt.figure(figsize=(16,5))
plt.title('Análise das ações da Magalu - Fechamento', fontsize=12, loc='left')
plt.plot(dados.index, dados['Fechamento']);

plt.xlabel('Período da Cotação', fontsize=12)
plt.ylabel('Valor da Ação (R$)', fontsize=12);

media_movel = dados['Fechamento'].rolling(5).mean()
media_tendencia = dados['Fechamento'].rolling(30).mean()

plt.style.use('fivethirtyeight')
plt.figure( figsize=(16,5) )
plt.title('Análise das Ações da Magalu - Fechamento', fontsize=15, loc='left')

plt.plot( dados.index, dados['Fechamento'] )
plt.plot( dados.index, media_movel)
plt.plot( dados.index, media_tendencia);

plt.xlabel('Período de Cotação', fontsize=12)
plt.ylabel('Valor da Ação (R$)', fontsize=12);

plt.figure( figsize=(8,4))
sns.boxplot( data=dados, x='Fechamento');

plt.xlabel('Valor da Ação (R$)', fontsize=12)

dados.columns

# Boxplot Mensal

dados['Mes'] = acoes_magalu['Data'].dt.month

plt.figure( figsize=(16,5))
sns.boxplot( data=acoes_magalu, x='Mes', y='Fechamento')

plt.xlabel('Mês', fontsize=12)
plt.ylabel('Valor da Ação (R$)', fontsize=12);

acoes_magalu.groupby('Mes').describe()['Fechamento']

# Utilizando a Biblioteca go

Grafico = go.Figure (
    data=[
        go.Candlestick(
            x=dados.index,
            open = dados['Abertura'],
            high = dados['Maior'],
            low = dados['Menor'],
            close = dados['Fechamento'],
        )
    ]
)

Grafico.update_layout( xaxis_rangeslider_visible=False )

Grafico.show()

